# Generated by Django 4.1.4 on 2023-02-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
