# Generated by Django 4.2 on 2023-05-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PREPARING', 'Preparing'), ('SERVING', 'Serving'), ('DONE', 'Done')], default='PAID'),
        ),
    ]
